# Generated by Django 5.2 on 2025-04-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
